language: python
python:
  - 3.9
install:
  - pip installl -r requirements-dev.txt codecov
name: Coverage
  env:
    CODECOV_TOKEN='26b4e3d6-bac6-40e9-895b-b6ccaf40093f'
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov


