on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pipenv codecov
          pip installl -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          pipenv run flake8 .

      - name: Test with pytest
        run: pipenv run pytest libpythonpro --cov=libpythonpro

      - name: Posting Coverage
        run: pipenv run codecov
