on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pipenv codecov
          pip install -r requirements-dev.txt

      - name: Test with pytest
        run: pipenv run pytest libpythonpro --cov=libpythonpro

      - name: Coverage token
        env:
          CODECOV_TOKEN: 26b4e3d6-bac6-40e9-895b-b6ccaf40093f

      - name: Posting Coverage
        run: pipenv run codecov
